'use strict';

const AUTOGENERATED_DIALOG_PREFIX = 'FormFlow_AutoResolved_';
const uuid = require('node-uuid');

const FormFlow = require('../');
module.exports = function ( session, value ) {
  let dialogId;
  let isDialog = Array.isArray(value) || ("function" == typeof value);
  if ( isDialog ) {
    dialogId = AUTOGENERATED_DIALOG_PREFIX + uuid.v4();
    session.library.dialog(dialogId, value);

  } else if ("object" == typeof value ) {
    let config = [value];
    dialogId = AUTOGENERATED_DIALOG_PREFIX + uuid.v4();
    FormFlow.create(session.library, dialogId,config)
  } else if ("string" == typeof ( value )) {
    dialogId = value;
  } else {
    throw new Error('Failed to autogenerate form flow');
  }
  return dialogId;
}